# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/LN_Digital_Emulator.ui'
#
# Created: Wed Jan 21 10:47:05 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LN_DigitalEmulatorWindow(object):
    def setupUi(self, LN_DigitalEmulatorWindow):
        LN_DigitalEmulatorWindow.setObjectName("LN_DigitalEmulatorWindow")
        LN_DigitalEmulatorWindow.resize(322, 335)
        LN_DigitalEmulatorWindow.setMinimumSize(QtCore.QSize(322, 335))
        LN_DigitalEmulatorWindow.setMaximumSize(QtCore.QSize(322, 335))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Lemaker_logo_smallcrop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LN_DigitalEmulatorWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(LN_DigitalEmulatorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LN_DigitalImageLabel = QtGui.QLabel(self.centralwidget)
        self.LN_DigitalImageLabel.setEnabled(True)
        self.LN_DigitalImageLabel.setGeometry(QtCore.QRect(10, 5, 301, 201))
        self.LN_DigitalImageLabel.setText("")
        self.LN_DigitalImageLabel.setPixmap(QtGui.QPixmap(":/images/LN_Digital.png"))
        self.LN_DigitalImageLabel.setIndent(-1)
        self.LN_DigitalImageLabel.setObjectName("LN_DigitalImageLabel")
        self.outputControlBox = QtGui.QGroupBox(self.centralwidget)
        self.outputControlBox.setEnabled(False)
        self.outputControlBox.setGeometry(QtCore.QRect(10, 210, 301, 91))
        self.outputControlBox.setFlat(False)
        self.outputControlBox.setObjectName("outputControlBox")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.outputControlBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 281, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.allOnButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.allOnButton.setObjectName("allOnButton")
        self.horizontalLayout_2.addWidget(self.allOnButton)
        self.allOffButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.allOffButton.setObjectName("allOffButton")
        self.horizontalLayout_2.addWidget(self.allOffButton)
        self.flipButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.flipButton.setObjectName("flipButton")
        self.horizontalLayout_2.addWidget(self.flipButton)
        self.horizontalLayoutWidget = QtGui.QWidget(self.outputControlBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 281, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output7Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output7Button.setCheckable(True)
        self.output7Button.setChecked(False)
        self.output7Button.setObjectName("output7Button")
        self.horizontalLayout.addWidget(self.output7Button)
        self.output6Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output6Button.setCheckable(True)
        self.output6Button.setObjectName("output6Button")
        self.horizontalLayout.addWidget(self.output6Button)
        self.output5Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output5Button.setCheckable(True)
        self.output5Button.setObjectName("output5Button")
        self.horizontalLayout.addWidget(self.output5Button)
        self.output4Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output4Button.setCheckable(True)
        self.output4Button.setObjectName("output4Button")
        self.horizontalLayout.addWidget(self.output4Button)
        self.output3Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output3Button.setCheckable(True)
        self.output3Button.setObjectName("output3Button")
        self.horizontalLayout.addWidget(self.output3Button)
        self.output2Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output2Button.setCheckable(True)
        self.output2Button.setObjectName("output2Button")
        self.horizontalLayout.addWidget(self.output2Button)
        self.output1Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output1Button.setCheckable(True)
        self.output1Button.setObjectName("output1Button")
        self.horizontalLayout.addWidget(self.output1Button)
        self.output0Button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.output0Button.setCheckable(True)
        self.output0Button.setObjectName("output0Button")
        self.horizontalLayout.addWidget(self.output0Button)
        self.led7Label = QtGui.QLabel(self.centralwidget)
        self.led7Label.setEnabled(True)
        self.led7Label.setGeometry(QtCore.QRect(90, 50, 16, 21))
        self.led7Label.setMidLineWidth(-2)
        self.led7Label.setText("")
        self.led7Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led7Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led7Label.setMargin(0)
        self.led7Label.setIndent(-1)
        self.led7Label.setObjectName("led7Label")
        self.led5Label = QtGui.QLabel(self.centralwidget)
        self.led5Label.setGeometry(QtCore.QRect(114, 50, 16, 21))
        self.led5Label.setText("")
        self.led5Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led5Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led5Label.setMargin(0)
        self.led5Label.setIndent(-1)
        self.led5Label.setObjectName("led5Label")
        self.led1Label = QtGui.QLabel(self.centralwidget)
        self.led1Label.setGeometry(QtCore.QRect(163, 50, 16, 21))
        self.led1Label.setText("")
        self.led1Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led1Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led1Label.setMargin(0)
        self.led1Label.setIndent(-1)
        self.led1Label.setObjectName("led1Label")
        self.led0Label = QtGui.QLabel(self.centralwidget)
        self.led0Label.setGeometry(QtCore.QRect(175, 50, 16, 21))
        self.led0Label.setText("")
        self.led0Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led0Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led0Label.setMargin(0)
        self.led0Label.setIndent(-1)
        self.led0Label.setObjectName("led0Label")
        self.led3Label = QtGui.QLabel(self.centralwidget)
        self.led3Label.setGeometry(QtCore.QRect(139, 50, 16, 21))
        self.led3Label.setText("")
        self.led3Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led3Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led3Label.setMargin(0)
        self.led3Label.setIndent(-1)
        self.led3Label.setObjectName("led3Label")
        self.led4Label = QtGui.QLabel(self.centralwidget)
        self.led4Label.setGeometry(QtCore.QRect(127, 50, 16, 21))
        self.led4Label.setText("")
        self.led4Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led4Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led4Label.setMargin(0)
        self.led4Label.setIndent(-1)
        self.led4Label.setObjectName("led4Label")
        self.led2Label = QtGui.QLabel(self.centralwidget)
        self.led2Label.setGeometry(QtCore.QRect(152, 50, 16, 21))
        self.led2Label.setText("")
        self.led2Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led2Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led2Label.setMargin(0)
        self.led2Label.setIndent(-1)
        self.led2Label.setObjectName("led2Label")
        self.led6Label = QtGui.QLabel(self.centralwidget)
        self.led6Label.setGeometry(QtCore.QRect(100, 50, 16, 21))
        self.led6Label.setText("")
        self.led6Label.setPixmap(QtGui.QPixmap(":/images/LN_led_on.png"))
        self.led6Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.led6Label.setMargin(0)
        self.led6Label.setIndent(-1)
        self.led6Label.setObjectName("led6Label")
        LN_DigitalEmulatorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LN_DigitalEmulatorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 322, 25))
        self.menubar.setObjectName("menubar")
        self.menuEnable = QtGui.QMenu(self.menubar)
        self.menuEnable.setObjectName("menuEnable")
        self.menuAddress = QtGui.QMenu(self.menubar)
        self.menuAddress.setObjectName("menuAddress")
        LN_DigitalEmulatorWindow.setMenuBar(self.menubar)
        self.actionSPI_Visualiser = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.actionSPI_Visualiser.setObjectName("actionSPI_Visualiser")
        self.outputControlAction = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.outputControlAction.setCheckable(True)
        self.outputControlAction.setObjectName("outputControlAction")
        self.inputPullupsAction = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.inputPullupsAction.setCheckable(True)
        self.inputPullupsAction.setChecked(True)
        self.inputPullupsAction.setObjectName("inputPullupsAction")
        self.board0Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.board0Action.setCheckable(True)
        self.board0Action.setChecked(True)
        self.board0Action.setObjectName("board0Action")
        self.board1Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.board1Action.setCheckable(True)
        self.board1Action.setObjectName("board1Action")
        self.board2Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.board2Action.setCheckable(True)
        self.board2Action.setObjectName("board2Action")
        self.board3Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.board3Action.setCheckable(True)
        self.board3Action.setObjectName("board3Action")
        self.LN_DigitalAction = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.LN_DigitalAction.setCheckable(True)
        self.LN_DigitalAction.setChecked(True)
        self.LN_DigitalAction.setObjectName("LN_DigitalAction")
        self.LN_Digital2Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.LN_Digital2Action.setCheckable(True)
        self.LN_Digital2Action.setObjectName("LN_Digital2Action")
        self.address0Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.address0Action.setCheckable(True)
        self.address0Action.setObjectName("address0Action")
        self.address1Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.address1Action.setCheckable(True)
        self.address1Action.setObjectName("address1Action")
        self.address2Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.address2Action.setCheckable(True)
        self.address2Action.setObjectName("address2Action")
        self.address3Action = QtGui.QAction(LN_DigitalEmulatorWindow)
        self.address3Action.setCheckable(True)
        self.address3Action.setObjectName("address3Action")
        self.menuEnable.addAction(self.outputControlAction)
        self.menuEnable.addSeparator()
        self.menuEnable.addAction(self.inputPullupsAction)
        self.menuAddress.addAction(self.address0Action)
        self.menuAddress.addAction(self.address1Action)
        self.menuAddress.addAction(self.address2Action)
        self.menuAddress.addAction(self.address3Action)
        self.menubar.addAction(self.menuEnable.menuAction())
        self.menubar.addAction(self.menuAddress.menuAction())

        self.retranslateUi(LN_DigitalEmulatorWindow)
        QtCore.QMetaObject.connectSlotsByName(LN_DigitalEmulatorWindow)

    def retranslateUi(self, LN_DigitalEmulatorWindow):
        LN_DigitalEmulatorWindow.setWindowTitle(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "LN Digital Emulator", None, QtGui.QApplication.UnicodeUTF8))
        self.outputControlBox.setTitle(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Output Control", None, QtGui.QApplication.UnicodeUTF8))
        self.allOnButton.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "All on", None, QtGui.QApplication.UnicodeUTF8))
        self.allOffButton.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "All off", None, QtGui.QApplication.UnicodeUTF8))
        self.flipButton.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Flip", None, QtGui.QApplication.UnicodeUTF8))
        self.output7Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.output6Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.output5Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.output4Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.output3Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.output2Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.output1Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.output0Button.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEnable.setTitle(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAddress.setTitle(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSPI_Visualiser.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "SPI Visualiser", None, QtGui.QApplication.UnicodeUTF8))
        self.outputControlAction.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Output Control", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPullupsAction.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Input Pullups", None, QtGui.QApplication.UnicodeUTF8))
        self.board0Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Board 0", None, QtGui.QApplication.UnicodeUTF8))
        self.board1Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Board 1", None, QtGui.QApplication.UnicodeUTF8))
        self.board2Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Board 2", None, QtGui.QApplication.UnicodeUTF8))
        self.board3Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "Board 3", None, QtGui.QApplication.UnicodeUTF8))
        self.LN_DigitalAction.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "LN Digital", None, QtGui.QApplication.UnicodeUTF8))
        self.LN_Digital2Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "LN Digital v.2", None, QtGui.QApplication.UnicodeUTF8))
        self.address0Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.address1Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.address2Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.address3Action.setText(QtGui.QApplication.translate("LN_DigitalEmulatorWindow", "3", None, QtGui.QApplication.UnicodeUTF8))

import LN_Digital_Emulator.LN_Digital_Emulator_rc
